import { NextRequest, NextResponse } from 'next/server';
import OpenAI from 'openai';

// This API route accepts a JSON payload with a `prompt` property and
// returns an answer generated by OpenAI.  You can modify the prompt
// structure or use a different model by editing this file.  Make sure
// your OPENAI_API_KEY and OPENAI_MODEL environment variables are set.

export async function POST(req: NextRequest) {
  const body = await req.json();
  const prompt: string = body.prompt;
  const language: string | undefined = body.language;

  if (!prompt) {
    return NextResponse.json({ error: 'Missing prompt' }, { status: 400 });
  }

  const apiKey = process.env.OPENAI_API_KEY;
  const model = process.env.OPENAI_MODEL || 'gpt-3.5-turbo';
  if (!apiKey) {
    return NextResponse.json({ error: 'OpenAI API key not configured' }, { status: 500 });
  }

  const openai = new OpenAI({ apiKey });
  try {
    const messages: OpenAI.Chat.Completions.ChatCompletionMessageParam[] = [
      { role: 'system', content: 'You are an educational assistant helping Grade 12 learners understand Mathematics concepts.' },
      { role: 'user', content: prompt },
    ];
    if (language) {
      messages.push({ role: 'system', content: `Please answer in ${language}.` });
    }
    const completion = await openai.chat.completions.create({
      model,
      messages,
      max_tokens: 500,
    });
    const answer = completion.choices[0]?.message?.content?.trim() || '';
    return NextResponse.json({ answer });
  } catch (error: any) {
    return NextResponse.json({ error: error.message || 'Error generating answer' }, { status: 500 });
  }
}
