import { NextRequest, NextResponse } from 'next/server';
import OpenAI from 'openai';

// This API route accepts a JSON payload with a `prompt` property and
// returns an answer generated by OpenAI.  You can modify the prompt
// structure or use a different model by editing this file.  Make sure
// your OPENAI_API_KEY and OPENAI_MODEL environment variables are set.

export async function POST(req: NextRequest) {
  const body = await req.json();
  const prompt: string = body.prompt;
  const language: string | undefined = body.language;
  const topicContext: string | undefined = body.topicContext;

  if (!prompt) {
    return NextResponse.json({ error: 'Missing prompt' }, { status: 400 });
  }

  const apiKey = process.env.OPENAI_API_KEY;
  const model = process.env.OPENAI_MODEL || 'gpt-3.5-turbo';
  if (!apiKey) {
    return NextResponse.json({ error: 'OpenAI API key not configured' }, { status: 500 });
  }

  const openai = new OpenAI({ apiKey });
  try {
    const messages: OpenAI.Chat.Completions.ChatCompletionMessageParam[] = [
      {
        role: 'system',
        content:
          'You are an educational assistant for South African Grade 12 Mathematics (CAPS). Respond in simple language with step-by-step reasoning, highlight the relevant notes section, and give short feedback on common mistakes.',
      },
    ];
    if (language) {
      messages.push({
        role: 'system',
        content: `Please answer in ${language} and keep sentences short for translation clarity.`,
      });
    }
    if (topicContext) {
      messages.push({
        role: 'system',
        content: `Context from the topic page:\n${topicContext}`,
      });
    }
    messages.push({ role: 'user', content: prompt });
    const completion = await openai.chat.completions.create({
      model,
      messages,
      max_tokens: 500,
    });
    const answer = completion.choices[0]?.message?.content?.trim() || '';
    return NextResponse.json({ answer });
  } catch (error: any) {
    return NextResponse.json({ error: error.message || 'Error generating answer' }, { status: 500 });
  }
}
